services:
  db:
    image: postgres:latest
    container_name: storefront
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres:
